###NumPy

In [ ]:
#1. Create a NumPy array with values from 10 to 49 (inclusive).
# Reshape it into a 4x10 matrix.

import numpy as np
arr = np.array(range(10, 50))
arr=np.reshape(arr,(4,10))
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
# Then extract the last column from the reshaped matrix
print(arr[0:,9:])

[[19]
 [29]
 [39]
 [49]]


In [ ]:
#2. Create two 3×3 matrices:
# One filled with all 5s , One with values from 1 to 9
#  Then find the transpose of the result
frst=np.full((3,3),5)
print(frst)
scnd=np.array(range(1,10)).reshape(3,3)
print(scnd)



[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#  Add the two matrices
sum=np.add(frst,scnd)
sum

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#  Multiply them element-wise
product=np.multiply(frst,scnd)
product

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#  Then find the transpose of the result
trps=np.transpose(product)
# trps=product.T
trps

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [ ]:
# 3. Create a NumPy array of 15 random integers between 10 and 100.
rand=np.random.randint(10,101,15)
print(rand)

[19 94 61 94 85 34 34 43 11 74 77 61 82 60 25]


In [ ]:
# ● Replace all values greater than 50 with -1
rand[rand > 50]=-1
rand

array([19, -1, -1, -1, -1, 34, 34, 43, 11, -1, -1, -1, -1, -1, 25])

In [ ]:
# ● Count how many values were replaced.
count=np.sum(rand==-1)
print(count)

9


In [ ]:
# 4. Generate a 5×4 array with random values between 0 and 1 (float).
flt=np.random.rand(5,4)
flt


array([[0.21303402, 0.66283096, 0.77209295, 0.00615964],
       [0.79800437, 0.1910166 , 0.15548519, 0.98873936],
       [0.43131013, 0.55833178, 0.75430846, 0.56984394],
       [0.70741513, 0.36695303, 0.89992894, 0.7078697 ],
       [0.97599678, 0.60087903, 0.21480972, 0.74521809]])

In [ ]:
#  Find the row with the maximum sum of values.
rwsm=np.sum(flt,axis=1)
max_raw=np.argmax(rwsm)
mxrw=flt[max_raw]
mxrw

array([0.70741513, 0.36695303, 0.89992894, 0.7078697 ])

In [ ]:
#  Normalize each row using the formula:
min= flt.min(axis=1)
max=flt.max(axis=1)
min = min.reshape(-1, 1)
max = max.reshape(-1, 1)
normalized = (flt - min) / (max - min)
normalized


array([[0.27009451, 0.85734791, 1.        , 0.        ],
       [0.77109627, 0.04264174, 0.        , 1.        ],
       [0.        , 0.39325792, 1.        , 0.42889947],
       [0.63879454, 0.        , 1.        , 0.63964742],
       [1.        , 0.50719374, 0.        , 0.69681737]])

In [ ]:
# 5. arrr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#  Find all unique elements
arrr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print(np.unique(arrr))

[1 3 5 7 9]


In [ ]:
#  Find the duplicates (elements that appear more than once)
unique_elements,counts=np.unique(arrr, return_counts=True)
duplicates=unique_elements[counts>1]
print(duplicates)



[1 3 5]


In [ ]:
# 6. Create a 6×6 NumPy array with values from 1 to 36.
arr=np.array(range(1,37))
arr=np.reshape(arr,(6,6))
arr



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
# ● Extract the middle 4×4 submatrix.
submatrix=arr[1:5,1:5]
print(submatrix)

[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [ ]:
# ● Then extract all even numbers from this submatrix.
even=submatrix[submatrix%2==0]
print(even)

[ 8 10 14 16 20 22 26 28]


In [ ]:
# 7. Generate an array of shape (3, 4) with values from 0 to 11.
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# ● Reshape it to (2, 6)
reshaped_arr = arr.reshape(2, 6)
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# ● Then flatten it into a 1D array
flattened = reshaped_arr.flatten()   # makes a copy
# or
flattened = reshaped_arr.ravel()     # returns a view (faster if no copy needed)
# or
flattened = reshaped_arr.reshape(-1)
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# ● Convert the 1D array back to shape (4, 3)
print(flattened.reshape(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# 8 . Create an array: a = np.array([[1, 2], [3, 4]])
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
# ● Append a new row [5, 6]
result = np.append(a, [[5, 6]], axis=0)
result


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# ● Then append a new column [7, 8, 9]
new_column=np.array([ 7,8, 9])
new_column=np.reshape(new_column,(-1,1))
result2=np.append(result,new_column, axis=1)
print(result2)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
# 9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
# ● Join them into a single array
joined_array=np.concatenate((a,b,c))
print(joined_array)



[1 2 3 4 5 6 7 8 9]


In [ ]:
# ● Reshape the result into a 3×3 matrix
b=joined_array.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# ● Extract the diagonal elements
diagonal=np.diag(b)
diagonal

array([1, 5, 9])

In [ ]:
# 10. Create a NumPy array of integers from 1 to 20.
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# ● Extract all values that are divisible by 3 or 5.
div3_4=arr[(arr%3==0) | (arr%5==0)]
div3_4

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [ ]:
# ● Count how many such values exist.
# count= len(div3_4)
count = div3_4.size
count

9

###PANDAS

In [ ]:
# 1. Load the Titanic dataset and display the first 10 rows.
import seaborn as sns
import pandas as pd
df = sns.load_dataset('titanic')
print(df.head(10))


   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

In [ ]:
# Find the number of missing values in each column.
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# 3. Find the percentage of passengers who survived, grouped by gender.
survival_percentage = df.groupby('sex')['survived'].mean() * 100
print(survival_percentage)

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64


In [ ]:
# 4. Find the average, median, and standard deviation of passenger ages.
ages = df['age'].dropna()


average_age = ages.mean()
median_age = ages.median()
std_dev_age = ages.std()
print("Average ",average_age)
print("Median ",median_age)
print("Standard Deviation ",std_dev_age)

Average  29.69911764705882
Median  28.0
Standard Deviation  14.526497332334044


In [ ]:
# 5. Count how many passengers were in each class (pclass).
count=df['pclass'].count()
print(count)

891


In [ ]:
# 6. Show all passengers who were female, under age 18, and survived.
list = df[(df['sex'] == 'female') & (df['age'] < 18) & (df['survived'] == 1)]
list

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

In [ ]:
# 7. Replace missing age values with the median age.
median_age = df['age'].median()

data=df['age'] = df['age'].fillna(median_age)
print(data)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64


In [ ]:
# 8. Create a column age_group with values:
# a. 'Child' for age < 18
df['age'] = df['age'].fillna(df['age'].median())

d=df['age_group'] = df['age'].apply(lambda x: 'Child')
print(d)



0      Child
1      Child
2      Child
3      Child
4      Child
       ...  
886    Child
887    Child
888    Child
889    Child
890    Child
Name: age, Length: 891, dtype: object


In [ ]:
# b. 'Adult' for age 18–60
df['age'] = df['age'].fillna(df['age'].median())

# Define age_group column: Child (<18), Adult (18–60)
b=df['age_group'] = df['age'].apply(lambda x: 'Child' if x < 18 else 'Adult' if x <= 60 else 'Senior')
b

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...  
886    Adult
887    Adult
888    Adult
889    Adult
890    Adult
Name: age, Length: 891, dtype: object

In [ ]:
# c. 'Senior' for age > 60
df['age'] = df['age'].fillna(df['age'].median())

# Assign age groups
c=df['age_group'] = df['age'].apply(lambda x: 'Child' if x < 18 else 'Adult' if x <= 60 else 'Senior')
c

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...  
886    Adult
887    Adult
888    Adult
889    Adult
890    Adult
Name: age, Length: 891, dtype: object

In [ ]:
# 9.  Display the top 5 passengers who paid the highest fare.
top = df.sort_values(by='fare', ascending=False).head(5)
top

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

In [ ]:
# 10. Find the average fare paid, grouped by both pclass and sex.
avg_fare = df.groupby(['pclass', 'sex'])['fare'].mean().round(2)
print(avg_fare)

pclass  sex   
1       female    106.13
        male       67.23
2       female     21.97
        male       19.74
3       female     16.12
        male       12.66
Name: fare, dtype: float64


In [ ]:
# 11. Rename the following columns:
# a. 'sex' → 'gender'
df = df.rename(columns={'sex': 'gender'})
df

survived  pclass  gender   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  28.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone age_group  
0      man        True  NaN  Southampton    no  False     Adult  
1    woman       False    C    Cherbourg   yes  False     Adult  
2    woman       False  NaN  Southampton   yes   True     Adult  
3    woman       False    C  Southampton   yes  False     Adult  
4      man        True  NaN  Southampton    no   True     Adult  
..     ...         ...  ...          ...   ...    ...       ...  
886    man        True  NaN  Southampton    no   True     Adult  
887  woman       False    B  Southampton   yes   True     Adult  
888  woman       False  NaN  Southampton    no  False     Adult  
889    man        True    C    Cherbourg   yes   True     Adult  
890    man        True  NaN   Queenstown    no   True     Adult  

[891 rows x 16 columns]

In [ ]:
# b. 'fare' → 'ticket_fare'
df = df.rename(columns={
 'fare': 'ticket_fare'
})
df

survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  \
0           0       3    male  22.0      1      0       7.2500        S   
1           1       1  female  38.0      1      0      71.2833        C   
2           1       3  female  26.0      0      0       7.9250        S   
3           1       1  female  35.0      1      0      53.1000        S   
4           0       3    male  35.0      0      0       8.0500        S   
..        ...     ...     ...   ...    ...    ...          ...      ...   
886         0       2    male  27.0      0      0      13.0000        S   
887         1       1  female  19.0      0      0      30.0000        S   
888         0       3  female  28.0      1      2      23.4500        S   
889         1       1    male  26.0      0      0      30.0000        C   
890         0       3    male  32.0      0      0       7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone age_group  
0     Third    man        True  NaN  Southampton    no  False     Adult  
1     First  woman       False    C    Cherbourg   yes  False     Adult  
2     Third  woman       False  NaN  Southampton   yes   True     Adult  
3     First  woman       False    C  Southampton   yes  False     Adult  
4     Third    man        True  NaN  Southampton    no   True     Adult  
..      ...    ...         ...  ...          ...   ...    ...       ...  
886  Second    man        True  NaN  Southampton    no   True     Adult  
887   First  woman       False    B  Southampton   yes   True     Adult  
888   Third  woman       False  NaN  Southampton    no  False     Adult  
889   First    man        True    C    Cherbourg   yes   True     Adult  
890   Third    man        True  NaN   Queenstown    no   True     Adult  

[891 rows x 16 columns]

In [ ]:
# 12. Count the number of passengers who survived and didn’t survive, grouped by class.
survival_counts = df.groupby(['pclass', 'survived']).size().unstack(fill_value=0)
# Rename columns for clarity (optional)
survival_counts.columns = ['Not Survived', 'Survived']
print(survival_counts)

        Not Survived  Survived
pclass                        
1                 80       136
2                 97        87
3                372       119


In [ ]:
# 13. Find the average age of passengers grouped by both class and gender.
avg_age = df.groupby(['pclass', 'gender'])['age'].mean().round(2)
print(avg_age)

pclass  gender
1       female    33.98
        male      39.00
2       female    28.70
        male      30.51
3       female    23.57
        male      26.91
Name: age, dtype: float64
